#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source "$ROOT/scripts/env/load-root-env.sh"

export ALLOWED_ORIGINS="${NEXUS_DESIGNER_ALLOWED_ORIGINS:-http://127.0.0.1:8088,http://localhost:8088}"
export OUTPUTS_DIR="$ROOT/data/designer/outputs"
export TMP_DIR="$ROOT/data/designer/tmp"
export GEMINI_API_KEY="${NEXUS_GEMINI_API_KEY:-}"
export GOOGLE_API_KEY="${NEXUS_GOOGLE_API_KEY:-}"
export OPENAI_API_KEY="${NEXUS_OPENAI_API_KEY:-}"
export OPENAI_MODEL="${NEXUS_DESIGNER_OPENAI_MODEL:-gpt-4o-mini}"
export IMAGEN_MODEL="${NEXUS_DESIGNER_IMAGEN_MODEL:-imagen-4.0-generate-preview-06-06}"
export IMAGE_SIZE="${NEXUS_DESIGNER_IMAGE_SIZE:-1024x1024}"
export IMAGE_ASPECT_RATIO="${NEXUS_DESIGNER_IMAGE_ASPECT_RATIO:-1:1}"
export GEMINI_MODEL="${NEXUS_DESIGNER_GEMINI_MODEL:-gemini-2.5-pro}"
export GEMINI_PLANNER_MODEL="${NEXUS_DESIGNER_GEMINI_PLANNER_MODEL:-gemini-2.5-pro}"
export GEMINI_REFINER_MODEL="${NEXUS_DESIGNER_GEMINI_REFINER_MODEL:-}"
export GEMINI_VALIDATOR_MODEL="${NEXUS_DESIGNER_GEMINI_VALIDATOR_MODEL:-}"
export MAX_SAFETY_RETRIES="${NEXUS_DESIGNER_MAX_SAFETY_RETRIES:-3}"
export ENABLE_STEP1_PLANNER="${NEXUS_DESIGNER_ENABLE_STEP1_PLANNER:-true}"
export ENABLE_STEP2_PLANNER="${NEXUS_DESIGNER_ENABLE_STEP2_PLANNER:-true}"
export ENABLE_STEP3_PLANNER="${NEXUS_DESIGNER_ENABLE_STEP3_PLANNER:-true}"
export ENABLE_STEP3_PERSONA_LOCK_VALIDATION="${NEXUS_DESIGNER_ENABLE_STEP3_PERSONA_LOCK_VALIDATION:-true}"
export EXECUTOR_SINGLE_IMAGE_MODE="${NEXUS_DESIGNER_EXECUTOR_SINGLE_IMAGE_MODE:-true}"
export STEP3_MAX_CORRECTION_ROUNDS="${NEXUS_DESIGNER_STEP3_MAX_CORRECTION_ROUNDS:-2}"
export DELIVERY_SHARPEN_RADIUS="${NEXUS_DESIGNER_DELIVERY_SHARPEN_RADIUS:-1}"
export DELIVERY_SHARPEN_PERCENT="${NEXUS_DESIGNER_DELIVERY_SHARPEN_PERCENT:-150}"
export DELIVERY_SHARPEN_THRESHOLD="${NEXUS_DESIGNER_DELIVERY_SHARPEN_THRESHOLD:-3}"
export GENAI_MAX_RETRIES="${NEXUS_DESIGNER_GENAI_MAX_RETRIES:-3}"
export GENAI_MAX_RETRIES_RESOURCE_EXHAUSTED="${NEXUS_DESIGNER_GENAI_MAX_RETRIES_RESOURCE_EXHAUSTED:-6}"
export GENAI_RETRY_BASE_SECONDS="${NEXUS_DESIGNER_GENAI_RETRY_BASE_SECONDS:-2}"
export WORKER_THREADS="${NEXUS_DESIGNER_WORKER_THREADS:-2}"
export MIN_SECONDS_BETWEEN_PIECES="${NEXUS_DESIGNER_MIN_SECONDS_BETWEEN_PIECES:-0}"
export SUPABASE_URL="${NEXUS_DESIGNER_SUPABASE_URL:-}"
export SUPABASE_ANON_KEY="${NEXUS_DESIGNER_SUPABASE_ANON_KEY:-}"
export SUPABASE_SERVICE_ROLE_KEY="${NEXUS_DESIGNER_SUPABASE_SERVICE_ROLE_KEY:-}"
export SUPABASE_OUTPUTS_BUCKET="${NEXUS_SUPABASE_OUTPUTS_BUCKET:-image-gen-outputs}"
export SUPABASE_SIGNED_URL_EXPIRES_SECONDS="${NEXUS_SUPABASE_SIGNED_URL_EXPIRES_SECONDS:-604800}"
export SUPABASE_UPLOAD_MAX_ATTEMPTS="${NEXUS_SUPABASE_UPLOAD_MAX_ATTEMPTS:-3}"
export SUPABASE_UPLOAD_BACKOFF_SECONDS="${NEXUS_SUPABASE_UPLOAD_BACKOFF_SECONDS:-2}"

cd "$ROOT/apps/designer-api"
if [ ! -d .venv ]; then
  python3 -m venv .venv
fi
# shellcheck disable=SC1091
source .venv/Scripts/activate 2>/dev/null || source .venv/bin/activate
python -m pip install --upgrade pip >/dev/null
python -m pip install -r requirements.txt
python -m uvicorn api.app:app --host 0.0.0.0 --port "${NEXUS_DESIGNER_API_PORT:-8090}"
