#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source "$ROOT/scripts/env/load-root-env.sh"

export DATABASE_URL="${NEXUS_SUPABASE_DATABASE_URL:?NEXUS_SUPABASE_DATABASE_URL obrigatoria}"
export FAL_KEY="${NEXUS_PICTURE_FAL_KEY:?NEXUS_PICTURE_FAL_KEY obrigatoria}"
export ARTIFACT_INTERNAL_URL="${NEXUS_ARTIFACT_INTERNAL_URL:-http://127.0.0.1:8095}"
export ARTIFACT_INTERNAL_KEY="${NEXUS_ARTIFACT_INTERNAL_KEY:?NEXUS_ARTIFACT_INTERNAL_KEY obrigatoria}"
export PICTURE_INTERNAL_KEY="${NEXUS_PICTURE_INTERNAL_KEY:?NEXUS_PICTURE_INTERNAL_KEY obrigatoria}"
export PICTURE_DELEGATION_ACTIVE_KID="${NEXUS_PICTURE_DELEGATION_ACTIVE_KID:-v1}"
export PICTURE_DELEGATION_ACTIVE_KEY="${NEXUS_PICTURE_DELEGATION_ACTIVE_KEY:?NEXUS_PICTURE_DELEGATION_ACTIVE_KEY obrigatoria}"
export PICTURE_DELEGATION_PREVIOUS_KID="${NEXUS_PICTURE_DELEGATION_PREVIOUS_KID:-}"
export PICTURE_DELEGATION_PREVIOUS_KEY="${NEXUS_PICTURE_DELEGATION_PREVIOUS_KEY:-}"
export PICTURE_DELEGATION_ISSUER=nexus-chat-bridge
export PICTURE_DELEGATION_AUDIENCE=nexus-picture
export PICTURE_DELEGATION_MAX_TTL_SECONDS="${NEXUS_PICTURE_DELEGATION_MAX_TTL_SECONDS:-120}"
export PICTURE_WORKER_CONCURRENCY="${NEXUS_PICTURE_WORKER_CONCURRENCY:-1}"
export PICTURE_WORKER_LEASE_SECONDS="${NEXUS_PICTURE_WORKER_LEASE_SECONDS:-120}"
export PICTURE_WORKER_MAX_ATTEMPTS="${NEXUS_PICTURE_WORKER_MAX_ATTEMPTS:-3}"
export PICTURE_WORKER_HEARTBEAT_MS="${NEXUS_PICTURE_WORKER_HEARTBEAT_MS:-30000}"
export PICTURE_WORKER_POLL_MS="${NEXUS_PICTURE_WORKER_POLL_MS:-1000}"
export PICTURE_TEMP_ROOT="${PICTURE_TEMP_ROOT:-$ROOT/data/picture-temp}"
export PICTURE_PORT="${PICTURE_PORT:-8090}"

mkdir -p "$PICTURE_TEMP_ROOT"
cd "$ROOT/services/picture-it"
if [ ! -d node_modules ]; then
  bun install --frozen-lockfile
fi
exec bun run start:service
